steps:
  # build the container image
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '.' ]
  
  # push the container image to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']

#  # Deploy container image to Cloud Run
#  - name: gcr.io/cloud-builders/gcloud
#    args: ['beta', 'run', 'deploy', '${_RUN_APP_NAME}', '--image', 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID', '--region', '${_RUN_REGION}']

  - name: gcr.io/cloud-builders/kubectl
    args: ['set', 'image', 'deployment/${_APP_NAME}', '${_CONTAINER_NAME}=gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID']
    env:
    - 'CLOUDSDK_COMPUTE_ZONE=${_CLUSTER_REGION}'
    - 'CLOUDSDK_CONTAINER_CLUSTER=${_CLUSTER_NAME}'  

  
images:
- 'gcr.io/$PROJECT_ID/${_IMAGE_NAME}:$BUILD_ID'

substitutions:
    _IMAGE_NAME: gke-quickstart
    _APP_NAME: gke-quickstart-app
    _CONTAINER_NAME: gke-quickstart-sha256
    _CLUSTER_NAME: your-first-cluster-1
    _CLUSTER_REGION: us-central1-a
#    _RUN_APP_NAME: us-central1
#    _RUN_REGION: us-central1
    
options:
    substitution_option: 'ALLOW_LOOSE'